#ifndef STYLES_H
#define STYLES_H


#define COLOR_WHITE "#FFFFFF"
#define COLOR_BLACK "#EEEEEE"
#define COLOR_CELL_SELECTED "#88FF89"
#define COLOR_CELL_RESELECTABLE "#FFBBAA"

#define COLOR_PLAYER_1 "#CC6633"
#define COLOR_PRESSED_PLAYER_1 "#BB5522"
#define COLOR_DISABLED_PLAYER_1 "#AA4411"

#define COLOR_PLAYER_2 "#111144"
#define COLOR_PRESSED_PLAYER_2 "#DDDDAA"
#define COLOR_DISABLED_PLAYER_2 "#CCCC99"



#endif // STYLES_H
