#ifndef VARIABLES_H
#define VARIABLES_H

#define DESK_HEIGHT 8
#define DESK_WIDTH 8

#define DESK_PIXEL_HEIGHT 320
#define DESK_PIXEL_WIDTH 320

#define DESK_VERTICAL_OFFSET_PIXELS 100
#define DESK_HORIZONTAL_OFFSET_PIXELS 100

#define SCENE_WIDTH 640
#define SCENE_HEIGHT 480

#endif // VARIABLES_H
